on: [push]

jobs:
  meeting_nopes:
    runs-on: ubuntu-latest
    name: Testing meeting nopes!
    steps:
    - name: Meeting nopes
      id: nope
      uses: jamesmartin/meetingnopes@master
      with:
        template: 'some/file.md'
        project-column-id: '3559690' 
    # Use the output from the `hello` step
    - name: Get the PR URL
      run: echo "The PR is at ${{ steps.nope.outputs.pull-request-url }}"
